services:
  redis:
    image: redis:8.0-M04-bookworm
    container_name: redis
    networks:
      - thalamus-proxy
  proxyserver:
    build:
      context: ..
      dockerfile: cmd/proxy/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - thalamus-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - registrationserver
  registrationserver:
    build:
      context: ..
      dockerfile: cmd/registration/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - thalamus-proxy
    depends_on:
      - redis

networks:
  thalamus-proxy:
