services:
  redis:
    image: redis:8.0-M04-bookworm
    networks:
      - thalamus-proxy
  proxyserver:
    build:
      context: ..
      dockerfile: cmd/proxy/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - thalamus-proxy
  registrationserver:
    build:
      context: ..
      dockerfile: cmd/registration/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - thalamus-proxy

networks:
  thalamus-proxy:
